version: '3.8'

services:
  bible-site:
    build: .
    ports:
      - '8080:80'
    container_name: bible-static-site
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development service for live reloading
  bible-site-dev:
    build:
      context: .
      target: builder
    ports:
      - '8081:8080'
    container_name: bible-static-site-dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
    profiles:
      - dev
