name = "explore-scripture"
main = "src/worker.js"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

# Account settings (using environment variables)
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Environment variables
[vars]
ENVIRONMENT = "production"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "${CLOUDFLARE_KV_CACHE_ID}"
preview_id = "${CLOUDFLARE_KV_CACHE_PREVIEW_ID}"

[[kv_namespaces]]
binding = "ENTITIES"
id = "${CLOUDFLARE_KV_ENTITIES_ID}"
preview_id = "${CLOUDFLARE_KV_ENTITIES_PREVIEW_ID}"

# Static assets configuration
[site]
bucket = "_site"

# Build configuration
[build]
command = "npm run build:workers"
cwd = "./"

# Development settings
[dev]
local_protocol = "https"
port = 8787

# Routes
[[routes]]
pattern = "*bible-explorer.pages.dev/*"
zone_name = "pages.dev"

# Security headers
[env.production]
[env.production.vars]
CSP_HEADER = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: https:; connect-src 'self' https://api.esv.org https://www.biblegateway.com; frame-src https://www.youtube.com https://www.biblegateway.com;"

# Analytics
[[analytics_engine_datasets]]
binding = "BIBLE_ANALYTICS"
dataset = "explore_scripture_analytics"