name: Bible Explorer Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        python-version: [3.9, 3.11]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Node.js dependencies
      run: |
        npm ci
        npm run build
    
    - name: Setup Chrome for testing
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Create Python virtual environment
      run: |
        python -m venv test-env
        source test-env/bin/activate
        pip install -r tests/requirements.txt
    
    - name: Start development server
      run: |
        npm run dev &
        sleep 10
        curl -f http://localhost:8080 || exit 1
    
    - name: Run Selenium tests
      run: |
        source test-env/bin/activate
        python -m pytest tests/ \
          --html=test_report.html \
          --self-contained-html \
          -v \
          --tb=short
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report-node${{ matrix.node-version }}-py${{ matrix.python-version }}
        path: test_report.html
    
    - name: Upload screenshots on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots-node${{ matrix.node-version }}-py${{ matrix.python-version }}
        path: screenshots/